[4월 1주차/poemnow] like 로직 구현
poemnow/poemnow pull request #13
Opened 2023-04-09 03:48 UTC by Moon-hongwoong

1. 좋아요 기능 추가 
2. 좋아요 취소 기능 추가 
3. 내가 좋아요 누른 목록 보기 기능 추가
[추가로 할 것]
1. 변수 명 수정
2. userId를 세션에서 가져오는 것을 추가
3. 테스트 코드 추가(PostMan으로 확인은 하였음)
----------------------------------------------------
목록 보기 기능 구현 중 List<HashMap<String, String>>으로 했을 때 Integer -> String으로 될 수 없다고 나옴.
해결 방안으로 data type을 String -> Integer로 변경 했으나 이젠 String -> number가 될 수 없다고 나옴.
List<HashMap<?, ?>>로 변수명을 지정하지 않으니 정상동작하는 것을 확인할 수 있었습니다.

2023-04-17 12:57 UTC, E-Sangho reviewed
리뷰 끝냈습니다.

2023-04-17 12:57 UTC, E-Sangho commented on src/main/java/com/cgm/poemnow/controller/BookLikeController.java
> +        int response = booklikeService.addBookLike(likeRequest);
response가 0이면 BAD_REQUEST(400), 이나, INTERNAL_SERVER_ERROR(500)을 반환해야할 것 같습니다.

2023-04-17 12:57 UTC, E-Sangho commented on src/main/java/com/cgm/poemnow/controller/BookLikeController.java
> +        int response = booklikeService.removeBookLike(userId, bookId);
response가 0이면 BAD_REQUEST(400), 이나, NOT_FOUNT(404에러)사용하셔야 할 겉 같아요.

2023-04-17 12:57 UTC, E-Sangho commented on src/main/java/com/cgm/poemnow/controller/BookLikeController.java
> +        List<HashMap<?, ?>> response = booklikeService.findBookLike(userId);
response가 null이면 NOT_FOUNT(404에러)사용하셔야 할 겉 같아요.

2023-04-17 12:57 UTC, E-Sangho commented on src/main/java/com/cgm/poemnow/controller/CommentLikeController.java
> +        int response = CommentlikeService.addCommentLike(likeRequest);
response가 0이면 BAD_REQUEST(400), 이나, INTERNAL_SERVER_ERROR(500)을 반환해야할 것 같습니다.

2023-04-17 12:57 UTC, E-Sangho commented on src/main/java/com/cgm/poemnow/controller/CommentLikeController.java
> +        int response = CommentlikeService.removeCommentLike(userId, commentId);
response가 0이면 BAD_REQUEST(400), 이나, NOT_FOUNT(404에러)사용하셔야 할 겉 같아요.

2023-04-17 12:57 UTC, E-Sangho commented on src/main/java/com/cgm/poemnow/controller/CommentLikeController.java
> +        List<HashMap<?, ?>> response = CommentlikeService.findCommentLike(userId);
response가 0이면 BAD_REQUEST(400), 이나, NOT_FOUNT(404에러)사용하셔야 할 겉 같아요.

2023-04-17 12:57 UTC, E-Sangho commented on src/main/java/com/cgm/poemnow/controller/PoemLikeController.java
> +        int response = poemLikeService.addPoemLike(poemLikeRequest);
response가 0이면 BAD_REQUEST(400), 이나, INTERNAL_SERVER_ERROR(500)을 반환해야할 것 같습니다.

2023-04-17 12:57 UTC, E-Sangho commented on src/main/java/com/cgm/poemnow/controller/PoemLikeController.java
> +        int response = poemLikeService.removePoemLike(userId, poemId);
response가 0이면 BAD_REQUEST(400), 이나 NOT_FOUNT(404에러)사용하셔야 할 겉 같아요.

2023-04-17 12:57 UTC, E-Sangho commented on src/main/java/com/cgm/poemnow/controller/PoemLikeController.java
> +        List<HashMap<?, ?>> response = poemLikeService.findPoemLike(userId);
response가 0이면 BAD_REQUEST(400), 이나, NOT_FOUNT(404에러)사용하셔야 할 겉 같아요.

2023-04-17 12:57 UTC, E-Sangho commented on src/test/java/com/cgm/poemnow/controller/BookLikeControllerTest.java
> +                        .contentType(MediaType.APPLICATION_JSON)
여긴 잘 모르겠는데 줄 바꿈 간격이 맞나요?

2023-04-17 12:57 UTC, E-Sangho commented on src/test/java/com/cgm/poemnow/controller/BookLikeControllerTest.java
> +                        .content(userId))
여기도 간격 맞는지 잘 모르겠습니다.

2023-04-17 12:57 UTC, E-Sangho commented on src/test/java/com/cgm/poemnow/controller/PoemLikeControllerTest.java
> +
한 줄 지워주세요

2023-04-18 03:37 UTC, andbeyond0331 commented
현재 LikeController들이 PoemLikeController, BookLikeContoller, CommentLikeController로 되어 있는데, PoemController, BookController, CommentController와 헷갈릴 것 같다는 생각이 듭니다.

때문에 like 디렉토리를 새로 파서 그 안에 모아두는 게 좋을 것 같습니다. service와 mapper도 마찬가지입니다.

2023-04-18 05:56 UTC, jiwoob requested changes
전반적으로 코드 컨벤션 수정 한번 해주시면 좋을 것 같습니다!

2023-04-18 05:56 UTC, jiwoob commented on src/main/java/com/cgm/poemnow/mapper/BookLikeMapper.java
> +    int insertBookLike(BookLike likeRequest);
메서드는 한 줄씩 띄어서 써야할 것 같아요!

2023-04-18 05:56 UTC, jiwoob commented on src/main/java/com/cgm/poemnow/service/BookLikeService.java
> +    int addBookLike(BookLike likeRequest);
서비스 파일 메서드들도 띄어쓰기 봐주세요!

2023-04-18 05:56 UTC, jiwoob commented on src/main/java/com/cgm/poemnow/service/BookLikeServiceImpl.java
> +    @Override
serviceImpl에 여기도 한줄 띄어야 할 것 같아요!

2023-04-18 10:23 UTC, Batteryzz commented on src/test/java/com/cgm/poemnow/PoemnowApplicationTests.java
>  class PoemnowApplicationTests {
미정님이 다른 곳에도 적어주셨는데
1. 특별한 이슈가 없는 이상 본인이 작성한 파일 이외 파일은 commit에서 제외하기
2. 내용이 쓰이지 않은 메소드는 삭제하는 것이 좋습니다
라고 해주셨습니다

2023-04-19 12:26 UTC, BaeYoungSuk reviewed
모두 확인했습니다. 고생하셨습니다.

2023-04-30 01:53 UTC, merged