[4월 1주차/poemnow] book 로직 구현
poemnow/poemnow pull request #8
Opened 2023-04-03 05:00 UTC by andbeyond0331

# 개요
- book 로직 구현

## 외부 API endpoint 연결 고민

## 마이바티스
~~~ 혼자 공부했는데도 잘 안 돼서
~ 링크 참조했다

2023-04-09 06:21 UTC, rulrurara commented
안녕하세요

2023-04-09 06:22 UTC, BaeYoungSuk approved these changes

2023-04-17 11:51 UTC, E-Sangho reviewed
리뷰 끝냈습니다.

2023-04-17 11:51 UTC, E-Sangho commented on src/main/java/com/cgm/poemnow/controller/BookController.java
> +		int response = bookService.addBook(bookRequest);
response로 받아온 값이 0이라면 책이 추가되지 않았으므로 BadRequest를 반환하면 좋을 것 같습니다.

2023-04-17 11:51 UTC, E-Sangho commented on src/main/java/com/cgm/poemnow/controller/BookController.java
> +		return new ResponseEntity<>(response, HttpStatus.OK);
response가 null일 경우 찾는 책이 없으므로, NOT_FOUND를 반환하는게 좋을것 같아요.

2023-04-17 11:51 UTC, E-Sangho commented on src/main/java/com/cgm/poemnow/controller/BookController.java
> +		int response = bookService.modifyBook(book);
여기도 response가 0이면 BAD_REQUEST(400), 이나, INTERNAL_SERVER_ERROR(500)을 반환해야할 것 같습니다.

2023-04-17 11:51 UTC, E-Sangho commented on src/main/java/com/cgm/poemnow/controller/BookController.java
> +		int response = bookService.removeBook(id);
여기도 response가 0이면 BAD_REQUEST(400), 이나, INTERNAL_SERVER_ERROR(500)을 반환해야할 것 같습니다.

2023-04-17 11:51 UTC, E-Sangho commented on src/main/java/com/cgm/poemnow/domain/Book.java
> +	private Timestamp created_at;
이름을 createdAt으로 바꿔야 할 것 같아요

2023-04-17 11:51 UTC, E-Sangho commented on src/main/java/com/cgm/poemnow/domain/Book.java
> +	private Timestamp published_at;
publishedAt으로 고쳐야 할 것 같아요

2023-04-17 13:22 UTC, rulrurara reviewed
1. book에 poem들을 등록하는 insert 로직이 필요해 보여요
2. book에 poem들을 삭제하는 delete 로직이 필요해 보여요
3. 특정 book에 들어 있는 poem의 정보(title, content,like_cnt)를 select하는 로직이 필요해 보여요

2023-04-18 06:52 UTC, jiwoob requested changes
이렇게 로직 필요할 것 같습니다!

bookModify : 여기서 시를 추가, 삭제 필요
bookDetail : 여기서 시집 안에 시들까지 리스트로 불러오는 거 필요

2023-04-18 06:52 UTC, jiwoob commented on src/main/resources/mapper/BookMapper.xml
> +    <select id="selectBookById" parameterType="int" resultType="com.cgm.poemnow.domain.Book">
여기서 책 안에 있는 시들까지 가져와져야 할 것 같아요!

2023-04-18 10:10 UTC, Batteryzz commented on src/main/java/com/cgm/poemnow/controller/BookController.java
> +		Book book = Book.builder().id(id).title(title).build();
book은 빌더 사용하여 controller에서 이렇게 코드 짜도 되는 것일까요?

2023-04-19 01:43 UTC, andbeyond0331 commented on src/main/java/com/cgm/poemnow/controller/BookController.java
> +		Book book = Book.builder().id(id).title(title).build();
아니요! 아직 수정버전 push 전입니다 ㅠㅠ

2023-04-19 08:31 UTC, andbeyond0331 commented on src/main/java/com/cgm/poemnow/domain/Book.java
> +	private Timestamp created_at;
반영했습니다

2023-04-19 08:32 UTC, andbeyond0331 commented on src/main/java/com/cgm/poemnow/domain/Book.java
> +	private Timestamp published_at;
반영했습니다!

2023-04-19 08:34 UTC, andbeyond0331 commented on src/main/resources/mapper/BookMapper.xml
> +    <select id="selectBookById" parameterType="int" resultType="com.cgm.poemnow.domain.Book">
시집  따로 시집 하나 기준으로 시들 따로 불러오는 로직 추가 반영했습니다!

2023-04-19 08:34 UTC, andbeyond0331 commented on src/main/java/com/cgm/poemnow/controller/BookController.java
> +		Book book = Book.builder().id(id).title(title).build();
반영했습니다!

2023-04-19 08:35 UTC, andbeyond0331 commented
@rulrurara 말씀해주신 부분 반영되었습니다! 룰루랄라님! ᕦ( ᐛ )ᕡ

2023-04-19 08:57 UTC, E-Sangho reviewed
thorws와 관련된 리뷰를 올렸습니다. 확인 부탁드립니다.

2023-04-19 08:57 UTC, E-Sangho commented on src/main/java/com/cgm/poemnow/controller/BookController.java
> +		return new ResponseEntity<>(bookService.findBookById(id), HttpStatus.OK);
찾는 책이 없을 경우 HttpStatus.NOT_FOUND를 반환해야 합니다.

2023-04-19 08:57 UTC, E-Sangho commented on src/main/java/com/cgm/poemnow/controller/BookController.java
> +		return new ResponseEntity<>(bookService.findAllBooks(), HttpStatus.OK);
여긴 책을 찾을 수 없는 경우에도 잘못된게 아니여서 OK만 반환하는거죠?

2023-04-19 08:57 UTC, E-Sangho commented on src/main/java/com/cgm/poemnow/controller/BookController.java
> +		return new ResponseEntity<>(bookService.modifyBook(bookRequest), HttpStatus.OK);
업데이트 할 대상이 없는 경우 400이나 404 에러를 반환하는 것이 좋습니다.

2023-04-19 08:57 UTC, E-Sangho commented on src/main/java/com/cgm/poemnow/controller/BookController.java
> +		return new ResponseEntity<>(bookService.removeBook(id), HttpStatus.OK);
삭제할 대상이 없는 경우 400이나 404 에러를 반환하는 것이 좋습니다.

2023-04-19 08:57 UTC, E-Sangho commented on src/main/java/com/cgm/poemnow/service/book/BookServiceImpl.java
> +	public List<Poem> findPoemsByBookId(int id) { return bookMapper.selectPoemsByBookId(id); }
찾는 대상이 없을 경우 throws 로 에러를 일으키는게 좋습니다.

2023-04-19 08:57 UTC, E-Sangho commented on src/main/java/com/cgm/poemnow/service/book/BookServiceImpl.java
> +	public Book findBookById(int id) { return bookMapper.selectBookById(id); }
찾는 대상이 없을 경우 throws 로 에러를 일으키는게 좋습니다.

2023-04-19 08:57 UTC, E-Sangho commented on src/main/java/com/cgm/poemnow/service/book/BookServiceImpl.java
> +		return bookMapper.deleteBook(id);
삭제할 대상이 없는 경우 에러를 일으키는게 좋습니다.

2023-04-19 11:38 UTC, BaeYoungSuk reviewed
모두 확인했습니다. 고생하셨습니다.

2023-04-19 12:58 UTC, Batteryzz commented on src/main/java/com/cgm/poemnow/service/book/BookServiceImpl.java
> +		bookMapper.insertBook(book);
로직 이해가 부족해 질문 남깁니다!

여기서 북매퍼 인서트북이 돌아가면서 오토인크리로 북의 아이디값이 생성되었으므로
그 아이디 값을 가져와 리스트에 담긴 북포엠 set하여 부여했고, 그것을 맵에 담아 넘겨주는 흐름이 맞나요?!

2023-04-20 02:27 UTC, andbeyond0331 commented on src/main/java/com/cgm/poemnow/controller/BookController.java
> +		return new ResponseEntity<>(bookService.findBookById(id), HttpStatus.OK);
throws 관련 리뷰는 공통 부분 구현 후 전부 반영하겠습니다. 감사합니다

2023-04-20 02:29 UTC, andbeyond0331 commented on src/main/java/com/cgm/poemnow/service/book/BookServiceImpl.java
> +		bookMapper.insertBook(book);
오오 맞아요! 정확히 이해하셨습니다! 북이랑 북 포엠 테이블을 함께 건드리기에는 북이 새로 생성되어 AUTO_INCREMENT로 아이디가 생성되어야 북과 포엠을 연결할 수 있는 로직을 구현할 수 있기 때문에 북 먼저 생성 후 그 아이디를 받아와서 북포엠에 넣어준 겁니다!

2023-04-20 07:06 UTC, Moon-hongwoong approved these changes
고생 많으셨습니다.

2023-04-20 07:30 UTC, merged