[4월 1주차/poemnow] follow 로직 구현]
poemnow/poemnow pull request #9
Opened 2023-04-08 14:15 UTC by rulrurara

follow 인원수(카운트) 구현 해야 함!

2023-04-16 07:19 UTC, Batteryzz approved these changes
follow 로직 구현 확인했습니다.

2023-04-17 08:30 UTC, andbeyond0331 commented
개인적으로 드린 코드 리뷰와 테스트코드에 추가된 사항 반영해서 커밋 후 푸시 다시 하고 slack에 노티 부탁드립니다

2023-04-17 12:32 UTC, E-Sangho reviewed
리뷰 끝냈습니다.

2023-04-17 12:32 UTC, E-Sangho commented on src/main/java/com/cgm/poemnow/controller/FollowController.java
> +		int response = followService.addFollow(followRequest);
response가 0이면 BAD_REQUEST(400)을 반환해야 할 것 같습니다.

2023-04-17 12:32 UTC, E-Sangho commented on src/main/java/com/cgm/poemnow/controller/FollowController.java
> +		int response = followService.removeFollow(userId, followId);
여기도 response가 0이면 BAD_REQUEST(400), 이나, INTERNAL_SERVER_ERROR(500)을 반환해야할 것 같습니다.

2023-04-17 12:32 UTC, E-Sangho commented on src/main/java/com/cgm/poemnow/controller/FollowController.java
> +		response = followService.findFollow(userId);
response가 0이면 BAD_REQUEST(400)을 반환해야할 것 같습니다.

2023-04-17 12:32 UTC, E-Sangho commented on src/main/java/com/cgm/poemnow/controller/FollowController.java
> +		response = followService.findFollower(userId);
response가 0이면 BAD_REQUEST(400), 이나, INTERNAL_SERVER_ERROR(500)을 반환해야할 것 같습니다.

2023-04-17 12:32 UTC, E-Sangho commented on src/main/java/com/cgm/poemnow/controller/FollowController.java
> +		response = followService.findFollowCnt(userId);
response가 0이면 BAD_REQUEST(400)을 반환해야할 것 같습니다.

2023-04-17 12:32 UTC, E-Sangho commented on src/main/java/com/cgm/poemnow/controller/FollowController.java
> +		response = followService.findFollowerCnt(userId);
response가 0이면 BAD_REQUEST(400)을 반환해야할 것 같습니다.

2023-04-17 12:32 UTC, E-Sangho commented on src/main/java/com/cgm/poemnow/service/FollowService.java
> +    int findFollowCnt(int userId);
들여쓰기 맞춰주셔야 할거 같아요

2023-04-18 02:45 UTC, andbeyond0331 commented on src/test/java/com/cgm/poemnow/PoemnowApplicationTests.java
특별한 이슈가 없는 이상 본인이 작성한 파일 이외 파일은 commit에서 제외하시기 바랍니다.

2023-04-18 07:07 UTC, jiwoob requested changes
리뷰 완료했습니다!

2023-04-18 07:07 UTC, jiwoob commented on src/main/java/com/cgm/poemnow/domain/Follow.java
> +	private int id;
유저 아이디, 팔로우 아이디 복합키로 설정하기로 했으니,
DB 바꾸신 후에 여기 id도 빼면 될 것 같아요!

2023-04-18 10:15 UTC, Batteryzz commented on src/main/java/com/cgm/poemnow/mapper/FollowMapper.java
> +    int selectFollowCnt(int userId);
들여쓰기 맞추어주세용

2023-04-19 11:45 UTC, BaeYoungSuk commented on src/main/java/com/cgm/poemnow/controller/FollowController.java
> +		int userId = 1; // httpsesion에서 받아오는 아이디
여기 userId = 1이나 아래 쪽에 2는 테스트 위해서 임시로 지정한 값인가요? 아니면 다른 의미가 있는 값인가요?

2023-04-19 11:45 UTC, BaeYoungSuk reviewed
모두 확인했습니다. 고생하셨습니다.

2023-04-20 07:04 UTC, Moon-hongwoong approved these changes
고생 많으셨습니다.

2023-04-20 13:06 UTC, rulrurara commented on src/main/java/com/cgm/poemnow/controller/FollowController.java
> +		int userId = 1; // httpsesion에서 받아오는 아이디
session에서 받아올 값을 임시로 지정한 값입니다!

2023-04-22 07:47 UTC, andbeyond0331 reviewed
유저 프로필 눌렀을 때 팔로워, 팔로잉 목록들도 볼 수 있게 해야할 것 같아서
세션에서 받아온 게 아니라 특정 아이디로 검색해서 셀렉트 해올 수 있는 로직이 필요할 것 같습니다. 
mapper는 그대로 두고 controller에서 주는 거만 다르게 메서드 하나 추가해서 같은 거 호출하면 될 것 같네요!

2023-04-22 11:40 UTC, jiwoob approved these changes
수고하셨습니다!

2023-04-25 07:25 UTC, Batteryzz approved these changes

2023-04-25 07:35 UTC, merged